service: bref-demo

provider:
    name: aws
    region: us-east-2
    runtime: php-81
    logs:
        restApi: true
    apiGateway:
        binaryMediaTypes:
            - '*/*'

plugins:
    - ./index.js

package:
    patterns:
        - '!**'
        - 'demo/**'
        - 'src/**'
        - 'vendor/**'

functions:
    function:
        handler: demo/function.php
        description: 'Bref function demo'
        environment:
            BREF_LOOP_MAX: 100

    http:
        handler: demo/http.php
        runtime: php-81-fpm
        architecture: arm64
        description: 'Bref HTTP demo'
        timeout: 5 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            -   http: 'ANY /'

    psr7:
        handler: demo/psr7.php
        description: 'Bref HTTP demo with a PSR-7 handler'
        timeout: 5 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            -   http: 'ANY /psr7'
            -   httpApi: 'GET /psr7'
        environment:
            BREF_LOOP_MAX: 100

    http-api:
        handler: demo/http.php
        runtime: php-81-fpm
        description: 'Bref HTTP demo'
        timeout: 5 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            -   httpApi: '*'

    console:
        handler: demo/console.php
        runtime: php-81-console
        description: 'Bref console command demo'
        timeout: 5
