name: Build Docker images

# Ignore the v2 branch
on: workflow_dispatch

jobs:
  publish:
    name: Building images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images
        run: make docker-images
