name: Build Docker images

on:
  pull_request:
    paths:
      - runtime/**
    # Ignore the v2 branch
    branches-ignore:
      - v2

jobs:
  publish:
    name: Building images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images
        run: make docker-images
