name: Website

on:
    push:
        branches: [ 'website-v3' ]

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:

    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   run: npm install --global vercel@latest
            -   name: Pull Vercel Environment Information
                run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            -   name: Build
                run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            -   name: Deploy
                run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
